#!/bin/bash
# 103-water_and_stir: Add numbers in custom bases and convert result
printf "%o\n" $(( 5#$( echo $WATER | tr 'water' '01234') + 5#$( echo $STIR | tr 'stir.' '01234') )) | tr '01234567' 'bestchol'